name: Python CI

on: [push]

env:
  PYTHONPATH: "src"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev,deploy]"

      - name: Package metadata
        id: metadata
        run: |
          echo "PACKAGE_VERSION=$(python -c 'import mse_lib_sgx; print(mse_lib_sgx.__version__)')" >> $GITHUB_OUTPUT

      - name: Code format with black
        run: |
          python -m black --check $PYTHONPATH

      - name: Import check with isort
        run: |
          python -m isort --check $PYTHONPATH

      - name: Lint check with pylint
        run: |
          python -m pylint $PYTHONPATH

      - name: Lint check with pycodestyle
        run: |
          python -m pycodestyle $PYTHONPATH

      - name: Lint check with pydocstyle
        run: |
          python -m pydocstyle $PYTHONPATH

      - name: Typecheck with MyPy
        run: |
          python -m mypy $PYTHONPATH

      - name: Test with pytest
        run: |
          python -m pytest

      - name: Build package
        if: ${{ startsWith(github.ref, 'refs/tags') && endsWith(github.ref, steps.metadata.outputs.PACKAGE_VERSION) }}
        run: python -m build

      - name: Publish package to PyPi
        if: ${{ startsWith(github.ref, 'refs/tags') && endsWith(github.ref, steps.metadata.outputs.PACKAGE_VERSION) }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          print-hash: true
          password: ${{ secrets.PYPI_API_TOKEN }}
